DOMAIN = "scene_presets"
NAME = "Scene Presets"

PANEL_URL = "/scene_presets_panel.js"

SERVICE_APPLY_PRESET = "apply_preset"
SERVICE_APPLY_RANDOM_PRESET = "apply_random_preset"
SERVICE_APPLY_EFFECT = "apply_effect"
SERVICE_START_DYNAMIC_SCENE = "start_dynamic_scene"
SERVICE_STOP_DYNAMIC_SCENE = "stop_dynamic_scene"
SERVICE_STOP_ALL_DYNAMIC_SCENES = "stop_all_dynamic_scenes"
SERVICE_STOP_DYNAMIC_SCENES_FOR_TARGETS = "stop_dynamic_scenes_for_targets"
SERVICE_GET_DYNAMIC_SCENES = "get_dynamic_scenes"
SERVICE_START_CIRCADIAN = "start_circadian"
SERVICE_STOP_CIRCADIAN = "stop_circadian"
SERVICE_SET_SCHEDULE = "set_schedule"
SERVICE_CLEAR_SCHEDULE = "clear_schedule"
SERVICE_GET_SCHEDULE = "get_schedule"
SERVICE_EXPORT_PRESETS = "export_presets"
SERVICE_IMPORT_PRESETS = "import_presets"
SERVICE_GENERATE_EFFECT_PRESETS = "generate_effect_presets"

ATTR_SCENE_PRESET_ID = "preset_id"
ATTR_CATEGORY_ID = "category_id"
ATTR_TARGETS = "targets"
ATTR_BRIGHTNESS = "brightness"
ATTR_TRANSITION = "transition"
ATTR_SHUFFLE = "shuffle"
ATTR_SMART_SHUFFLE = "smart_shuffle"
ATTR_INTERVAL = "interval"
ATTR_EFFECT = "effect"
ATTR_WLED_PRESET = "wled_preset"
ATTR_WLED_PALETTE = "wled_palette"
ATTR_WLED_SPEED = "wled_speed"
ATTR_WLED_INTENSITY = "wled_intensity"

ATTR_DYNAMIC_SCENE_ID = "id"
ATTR_PAYLOAD = "payload"
ATTR_ENTITY_ID = "entity_id"

SIGNAL_PRESETS_CHANGED = "scene_presets_presets_changed"
